### ISSUE TITLE
Create a website that would serve as a collection for all the notes that are being stored. 

### ISSUE THREAD

**Issue by allanoguis** [allanoguis/coding-notes#11]
build a website that reads markdown and outputs to the page.

Please note: we can subdivide issues that revolve around this topic to make it easier for us to build

**Comment by khd33j** [comment]
I'd like to contribute to this. I can build the basic structure (HTML and CSS) for the site. For now, I think we should follow this design (https://www.framer.com/motion/introduction/), since that's what the repo's reference is. I would need further guidance regarding design choices (like color palette - going , etc) later.

**Comment by allanoguis** [comment]
The Framer Motion just happened to be on top. No order necessary because we have a vast scope for notes. But it's fine, let's go with your idea.

**Comment by KhanjarSingh** [comment]
hey @allanoguis can u please assign this to me

**Comment by allanoguis** [comment]
Hi @KhanjarSingh what do you propose on building?
